In [ ]:
from scipy.optimize import linprog

### **1. 식품 유통 물류 최적화**  
한 식품 회사는 3개의 창고(창고 X, 창고 Y, 창고 Z)에서 3개의 슈퍼마켓(슈퍼마켓 1, 슈퍼마켓 2, 슈퍼마켓 3)으로 제품을 배송하고자 한다. 각 경로별 운송비와 창고별 공급량, 슈퍼마켓별 수요량이 다음과 같다. 총 운송비를 최소화하는 배송 계획을 수립하시오.  

| 구분  | 슈퍼마켓 1 | 슈퍼마켓 2 | 슈퍼마켓 3 | 총 공급량 |
|------|--------|--------|--------|--------|
| 창고 X | 10만원 | 15만원 | 25만원 | 60개 |
| 창고 Y | 12만원 | 18만원 | 20만원 | 50개 |
| 창고 Z | 14만원 | 8만원  | 22만원 | 40개 |
| **총 수요량** | **50개** | **40개** | **60개** |  

In [26]:
import numpy as np

In [29]:
# 비용함수
c = [
    10, 15, 25,
    12, 18, 20,
    14, 8, 22
]

# 부등식 제약조건 좌변
A_ub = [
    [1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1],
]
# 부등식 제약조건 우변
b_ub = [
    60, 50, 40,
]

# 등식 제약조건 좌변
A_eq = [
    [1, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
]
# 등식 제약조건 우변
b_eq = [
    50, 40, 60
]

bounds = [(0, None) for _ in range(9)]
result = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
result.x.reshape(3, 3)

array([[50.,  0., 10.],
       [ 0.,  0., 50.],
       [ 0., 40., -0.]])


---

### **2. 전자제품 물류비 최소화**  
한 전자제품 제조업체는 3개의 공장에서 3개의 대형 매장으로 제품을 배송한다. 운송비, 공장별 공급량, 매장별 수요량은 다음과 같다. 비용을 최소화하는 최적 운송 계획을 구하시오.

| 구분  | 매장 1 | 매장 2 | 매장 3 | 총 생산량 |
|------|--------|--------|--------|--------|
| 공장 A | 8만원 | 14만원 | 20만원 | 80개 |
| 공장 B | 16만원 | 10만원 | 12만원 | 50개 |
| 공장 C | 10만원 | 9만원  | 18만원 | 70개 |
| **총 수요량** | **60개** | **80개** | **60개** |

In [30]:
# 비용함수

c = [
    8, 14, 20,
    16, 10, 12,
    10, 9, 18
]

# 부등식 제약조건 좌변
A_ub = [
    [1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1],
]
# 부등식 제약조건 우변
b_ub = [
    80, 50, 70,
]

# 등식 제약조건 좌변
A_eq = [
    [1, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
]
# 등식 제약조건 우변
b_eq = [
    60, 80, 60
]
bounds = [(0, None) for _ in range(9)]
result = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
result.x.reshape(3, 3)

array([[60., 10., 10.],
       [ 0.,  0., 50.],
       [ 0., 70.,  0.]])


---

### **3. 의류 회사 배송비 최적화**  
3개의 의류 생산 공장에서 3개의 주요 판매점으로 배송할 때 최소 운송비를 구하시오.

| 구분  | 판매점 1 | 판매점 2 | 판매점 3 | 총 생산량 |
|------|--------|--------|--------|--------|
| 공장 A | 5만원 | 12만원 | 8만원 | 90개 |
| 공장 B | 10만원 | 4만원  | 6만원 | 70개 |
| 공장 C | 9만원 | 7만원  | 3만원 | 50개 |
| **총 수요량** | **50개** | **80개** | **80개** |

In [ ]:
# 비용함수
c = [
    5, 12, 8,
    10, 4, 6,
    9, 7, 3,
]

# 부등식 제약조건 좌변
A_ub = [
    [1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1],
]
# 부등식 제약조건 우변
b_ub = [
    60, 50, 40,
]

# 등식 제약조건 좌변
A_eq = [
    [1, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
]
# 등식 제약조건 우변
b_eq = [
    50, 40, 60
]

bounds = [(0, None) for _ in range(9)]
result = linprog(c=c, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
result.x.reshape(3, 3)

array([[50., 10., 30.],
       [ 0., 70.,  0.],
       [ 0.,  0., 50.]])


---

### **4. 건축 자재 운송비 최소화**  
3개의 공장에서 3개의 건설 현장으로 건축 자재를 배송할 때 최적 운송 비용을 구하시오.

| 구분  | 현장 1 | 현장 2 | 현장 3 | 총 공급량 |
|------|--------|--------|--------|--------|
| 공장 X | 18만원 | 5만원  | 22만원 | 40개 |
| 공장 Y | 8만원  | 14만원 | 17만원 | 60개 |
| 공장 Z | 12만원 | 16만원 | 10만원 | 70개 |
| **총 수요량** | **50개** | **60개** | **60개** |

In [31]:
# 비용함수
c = [
    18, 5, 22,
    8, 14, 17,
    12, 16, 10,
]

# 부등식 제약조건 좌변
A_ub = [
    [1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1],
]
# 부등식 제약조건 우변
b_ub = [
    40, 60, 70
]

# 등식 제약조건 좌변
A_eq = [
    [1, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
]
# 등식 제약조건 우변
b_eq = [
    50, 60, 60
]

bounds = [(0, None) for _ in range(9)]
result = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
result.x.reshape(3, 3)

array([[ 0., 40.,  0.],
       [50., 10.,  0.],
       [ 0., 10., 60.]])


---

### **5. 신선식품 물류 최적화**  
신선식품을 보관하는 3개의 물류센터에서 3개의 대형 마트로 제품을 배송하는 최적 비용을 구하시오.

| 구분  | 마트 1 | 마트 2 | 마트 3 | 총 공급량 |
|------|--------|--------|--------|--------|
| 물류센터 A | 6만원 | 9만원 | 15만원 | 50개 |
| 물류센터 B | 13만원 | 7만원  | 10만원 | 70개 |
| 물류센터 C | 11만원 | 5만원  | 8만원 | 80개 |
| **총 수요량** | **40개** | **80개** | **80개** |

In [ ]:
# 비용함수
c = [
    6, 9, 15,
    13, 7, 10,
    11, 5, 8,
]

# 부등식 제약조건 좌변
A_ub = [
    [1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1],
]
# 부등식 제약조건 우변
b_ub = [
    50, 70, 80
]

# 등식 제약조건 좌변
A_eq = [
    [1, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
]
# 등식 제약조건 우변
b_eq = [
    40, 80, 80
]

bounds = [(0, None) for _ in range(9)]
result = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)

result.x.reshape(3, 3)

array([[40., 10.,  0.],
       [ 0., 70.,  0.],
       [ 0., -0., 80.]])